[package]
name = "emoji-picker"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.8", package = "gtk4" }
libadwaita = "0.6"
once_cell = "1.19"
unicode-segmentation = "1.11"

[profile.release]
lto = true
codegen-units = 1
strip = true